### ISSUE TITLE
Is it still valid?

### ISSUE THREAD

**Issue by freaad** [flaviomauro/OWI-535-Robotic-Arm-with-Python#1]
Hello. I am looking for the Robotic arm example for education purpose.
does this code is still vaild? It looks like interesting.
Thank you for sharing.

**Comment by flaviomauro** [comment]
Hello @freaad, Yes it is still valid. 
I'm currently using it in a study/fun personal project with IBM Watson.

Please let me know if you have any questions.

**Comment by flaviomauro** [comment]
Yes it is still valid.
